Models/Category.cs
namespace Movie_MVC_app.Models
{
    public class Category
    {
        public int id { get; set; }
        public string Name { get; set; }
    }
}

Models/MovieCategoryModel.cs
using System.Collections.Generic;

namespace Movie_MVC_app.Models
{
    public class MovieCategoryModel
    {
        public Movies Movie { get; set; }
        public  IEnumerable<Movies> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

Models/Movies.cs
namespace Movie_MVC_app.Models
{
    public class Movies
    {
                public int id { get; set; }
                public string Name { get; set; }
                public string Description{get;set;}
                public string ImageUrl  {get;set;}
                public string shortDescription { get; set; }
                public int CategoryId { get; set; }
                
        
    }
}

Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Movie_MVC_app.Data;
using Movie_MVC_app.Models;

namespace Movie_MVC_app.Controllers
{
    public class HomeController:Controller
    {
        
        public IActionResult index(int? id)
        {
          //TODO: Implement Realistic Implementation
        /*   MovieCategoryModel model=new MovieCategoryModel();
          model.Movies=MovieRepository.Movies;
          model.Categories=CategoryRepository.Category;*/
          var movies=MovieRepository.Movies;
           
          if(id!=null){

              movies=movies.Where(i=>i.CategoryId==id).ToList();
          }
          return View(movies);
        }
        public IActionResult Contact()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        public IActionResult Details(int id)
        {
          MovieCategoryModel model=new MovieCategoryModel();
          model.Categories=CategoryRepository.Category;
          model.Movie=MovieRepository.getByID(id);
          return View(model.Movie);
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace Movie_MVC_app.Controllers
{
    public class MovieController:Controller
    {
        public IActionResult index()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        public IActionResult Create()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        public IActionResult Details()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        public IActionResult List()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
    }
}

ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Movie_MVC_app.Data;

namespace Movie_MVC_app.ViewComponents
{
    public class CategoryMenuViewComponent:ViewComponent
    {
        //RouteData.Values["action"]=index
        //RouteData.Values["controller"]=hhome
        //RouteData.Values["id"]=3
        public IViewComponentResult Invoke(){
            if(RouteData.Values["action"].ToString()=="Index")
                ViewBag.SelectedCategory=RouteData?.Values["id"];
            return View(CategoryRepository.Category);
        }
    }
}

Views/Home/_movies.cshtml
@model IEnumerable<Movies>

@foreach (var item in Model)
{
    
<div class="car-mb-3">
    <div class="row no-gutter">
        <div class="col-md-3">
            <img src="~/images/@item.ImageUrl" alt="@item.Description" class="card-img">
        </div>
        <div class="col-md-9">
            <div class="card-body">
                <h5 class=" card-title">
                    <a asp-action="Details" asp-controller="Home" asp-route-id="@item.id">@item.Name</a>
                    </h5>
                <p class="card-text">@item.Description</p>
                <p class="card-text"> 
                    <small class="text-muted"> 3 days ago</small>
                </p>
            </div>
        </div>
    </div>
</div>

}

Views/Home/contact.cshtml
<h1>Home/contact</h1>

Views/Home/details.cshtml
@model Movies
<div class="row">
    <div class="col-md-3">
      
      @await Component.InvokeAsync("CategoryMenu")
    </div>
       <div class="col-md-9">
           <div class="card-mb-3">
               <div class="card-body">
                   <div class="raw no-gutter">
                        <div class="col-md-4">
                            <img src="~/images/@Model.ImageUrl" alt="@Model.Description" class="card-img">
                        </div>
                        <div class="col-md-8">
                            
                                <h5 class=" card-title">
                                <a asp-action="Details" asp-controller="Home" asp-route-id="@Model.id">@Model.Name</a>
                                </h5>
                                <p class="card-text">@Model.Description</p>
                                <p class="card-text"> 
                                <small class="text-muted"> 3 days ago</small>
                                </p>

                        </div>
                   </div>
               </div>
           </div>
       </div>
</div>

Views/Home/index.cshtml
@model IEnumerable<Movies>
<div class="row">
    <div class="col-md-3">
        
       @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        @Html.Partial("_movies",Model)
     <!-- <partial name="_movies" model="Model.Movies"> -->
    </div>

</div>

Views/Movie/create.cshtml
<h1>Movies/create</h1>

Views/Movie/details.cshtml
<h1>movies/details</h1>

Views/Movie/index.cshtml
<h1>movie/index</h1>

Views/Movie/list.cshtml
<h1>movies/list</h1>

Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>
<div class="list-group">
    <a href="/" class="list-group-item list-group-item-action action">Tüm Kategoriler</a>
    @foreach (var item in Model)
    {
        <a asp-controller="Home" asp-action="index" asp-route-id="@item.id"
         class="list-group-item list-group-item-action @(ViewBag.SelectedCategory==item.id.ToString()?"active":"")">@item.Name</a>
    }
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="\modules\bootstrap\dist\css\bootstrap.min.css">
    <link rel="stylesheet" href="\css\style.css">
    <title>Document</title>
</head>
<body>
    <header>
        @Html.Partial("_navbar")
    </header>
    <main>
        <div class="container mt-4">
            @RenderBody()
        </div>
    </main>
    <footer>
        @Html.Partial("_footer")
    </footer>
    
</body>
</html>

Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3">
    <div class="container">
        <span class="text-muted">
            Foooter Content
        </span>
    </div>
</div>

Views/Shared/_menu.cshtml
@model IEnumerable<Category>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="#" class="list-group-item list-group-item-action action">@item.Name</a>
    }
    
</div>

Views/Shared/_navbar.cshtml
<div class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a href="/" class="navbar-brand">Movie App</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/login" class="nav-link">Login</a>
            </li>
            <li class="nav-item">
                <a href="/register" class="nav-link">Register</a>
            </li>
        </ul>
    </div>
</div>